sudo: required

language: c

services:
  - docker

before_install:
  - docker info
  - docker build -t stocksoftware/keycloak-sqlserver .

script:
  - docker run -it --rm stocksoftware/keycloak-sqlserver -v || true
